#!/usr/bin/env python
"""
Fennec AI ASCII Art Generator

This script converts a fennec fox image to colored ASCII art for terminal display.
Run this script with the path to your fennec image to generate the banner.

Usage:
    python generate_art.py /path/to/fennec_image.png
    python generate_art.py /path/to/fennec_image.png --columns 60
"""

import argparse
import sys
from pathlib import Path

try:
    from ascii_magic import AsciiArt
except ImportError:
    print("Error: ascii-magic not installed. Run: pip install ascii-magic")
    sys.exit(1)


def generate_ascii_art(image_path: str, columns: int = 70) -> str:
    """Convert an image to colored ASCII art string."""
    try:
        art = AsciiArt.from_image(image_path)
        # Get the ASCII string with ANSI color codes
        ascii_str = art.to_ascii(columns=columns, monochrome=False)
        return ascii_str
    except Exception as e:
        print(f"Error converting image: {e}")
        return None


def save_banner_module(ascii_art: str, output_path: Path):
    """Save the generated ASCII art to a Python module."""

    # Escape any backslashes and quotes in the art
    escaped_art = ascii_art.replace('\\', '\\\\').replace('"""', '\\"\\"\\"')

    module_content = f'''"""
Auto-generated Fennec ASCII Art Banner

This file was generated by generate_art.py from the fennec fox image.
Do not edit manually - regenerate using the script if needed.
"""

# ANSI colored ASCII art of the fennec fox
FENNEC_ART = """{escaped_art}"""

def get_art() -> str:
    """Return the fennec ASCII art string."""
    return FENNEC_ART
'''

    output_path.write_text(module_content)
    print(f"Saved banner to: {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate ASCII art from fennec fox image"
    )
    parser.add_argument(
        "image_path",
        help="Path to the fennec fox image (PNG, JPG, etc.)"
    )
    parser.add_argument(
        "--columns", "-c",
        type=int,
        default=70,
        help="Width in characters (default: 70)"
    )
    parser.add_argument(
        "--preview", "-p",
        action="store_true",
        help="Preview the art in terminal without saving"
    )
    parser.add_argument(
        "--output", "-o",
        default=None,
        help="Output file path (default: generated_art.py in branding folder)"
    )

    args = parser.parse_args()

    # Check image exists
    if not Path(args.image_path).exists():
        print(f"Error: Image not found: {args.image_path}")
        sys.exit(1)

    print(f"Converting image: {args.image_path}")
    print(f"Columns: {args.columns}")

    # Generate ASCII art
    ascii_art = generate_ascii_art(args.image_path, args.columns)

    if ascii_art is None:
        sys.exit(1)

    if args.preview:
        print("\n--- Preview ---\n")
        print(ascii_art)
        print("\n--- End Preview ---\n")
    else:
        # Save to module
        if args.output:
            output_path = Path(args.output)
        else:
            output_path = Path(__file__).parent / "generated_art.py"

        save_banner_module(ascii_art, output_path)
        print("\nTo use the generated art, update banner.py to import from generated_art.py")


if __name__ == "__main__":
    main()
