#!/usr/bin/env python
"""
Fennec AI CLI - Autonomous Penetration Testing Framework.

Usage:
    fennec scan --target URL            # Run a penetration test
"""

import argparse
import asyncio
import json
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional
from urllib.parse import urlparse

# Add project to path
project_dir = os.path.dirname(os.path.abspath(__file__))
if project_dir not in sys.path:
    sys.path.insert(0, project_dir)
parent_dir = os.path.dirname(project_dir)
if parent_dir not in sys.path:
    sys.path.insert(0, parent_dir)


class ReportGenerator:
    """Generates organized output reports from pentest runs."""

    def __init__(self, output_dir: Path, target_url: str, session_id: str):
        self.target_url = target_url
        self.session_id = session_id

        # Create timestamped folder
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        domain = urlparse(target_url).netloc.replace(":", "_")
        self.run_dir = output_dir / f"{timestamp}_{domain}"
        self.run_dir.mkdir(parents=True, exist_ok=True)

        # Create subdirectories
        (self.run_dir / "agents").mkdir(exist_ok=True)
        (self.run_dir / "findings").mkdir(exist_ok=True)
        (self.run_dir / "raw").mkdir(exist_ok=True)

        # Track agent outputs
        self.agent_logs: dict[str, list[dict]] = {
            "recon": [],
            "analyst": [],
            "pentester": [],
            "coder": [],
        }
        self.events: list[dict] = []
        self.subtasks: list[dict] = []
        self.findings: list[dict] = []
        self.final_result: Optional[dict] = None

    def log_event(self, event_type: str, data: dict, agent: str = "system"):
        """Log an event."""
        event = {
            "timestamp": datetime.now().isoformat(),
            "type": event_type,
            "agent": agent,
            "data": data,
        }
        self.events.append(event)

        if agent in self.agent_logs:
            self.agent_logs[agent].append(event)

    def set_subtasks(self, subtasks: list[dict]):
        """Set the task plan."""
        self.subtasks = subtasks

    def set_result(self, result: dict):
        """Set the final result."""
        self.final_result = result

    def add_finding(self, finding: dict):
        """Add a security finding."""
        self.findings.append(finding)

    def generate_reports(self):
        """Generate all output reports."""
        self._write_summary()
        self._write_agent_reports()
        self._write_findings()
        self._write_raw_events()
        print(f"\n Reports saved to: {self.run_dir}")

    def _write_summary(self):
        """Write main summary report."""
        content = f"""# Fennec AI Security Assessment Report

## Target Information
- **URL:** {self.target_url}
- **Session ID:** {self.session_id}
- **Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Executive Summary

"""
        if self.final_result:
            status = "Completed Successfully" if self.final_result.get("success") else "Completed with Issues"
            content += f"**Status:** {status}\n\n"
            content += f"**Summary:**\n{self.final_result.get('result', 'No summary available.')}\n\n"

        content += "## Task Plan\n\n"
        if self.subtasks:
            for i, task in enumerate(self.subtasks, 1):
                status_icon = {
                    "completed": "[x]",
                    "failed": "[!]",
                    "running": "[~]",
                    "pending": "[ ]",
                    "skipped": "[-]",
                }.get(task.get("status", "pending"), "[?]")
                content += f"{i}. {status_icon} **{task.get('title', 'Untitled')}** ({task.get('agent', 'unknown')})\n"
        else:
            content += "No tasks were defined.\n"

        content += "\n## Agent Activity Summary\n\n"
        for agent, logs in self.agent_logs.items():
            if logs:
                content += f"- **{agent.capitalize()}:** {len(logs)} actions\n"

        content += f"\n## Findings Overview\n\n"
        if self.findings:
            content += f"**Total Findings:** {len(self.findings)}\n\n"
            for finding in self.findings:
                severity = finding.get("severity", "info").upper()
                content += f"- [{severity}] {finding.get('title', 'Untitled')}\n"
        else:
            content += "No specific findings recorded.\n"

        content += "\n---\n*Generated by Fennec AI*\n"

        (self.run_dir / "summary.md").write_text(content)

    def _write_agent_reports(self):
        """Write individual agent reports."""
        for agent, logs in self.agent_logs.items():
            if not logs:
                continue

            content = f"""# {agent.capitalize()} Agent Report

## Session: {self.session_id}
## Target: {self.target_url}

---

## Activity Log

"""
            for log in logs:
                timestamp = log["timestamp"]
                event_type = log["type"]
                data = log["data"]

                content += f"### [{timestamp}] {event_type}\n\n"

                if event_type == "message":
                    content += f"{data.get('content', '')}\n\n"
                elif event_type == "tool_call":
                    content += f"**Tool:** `{data.get('name', 'unknown')}`\n"
                    content += f"**Arguments:**\n```json\n{json.dumps(data.get('args', {}), indent=2)}\n```\n\n"
                elif event_type == "tool_result":
                    content += f"**Result:**\n```\n{data.get('result', '')[:2000]}\n```\n\n"
                else:
                    content += f"```json\n{json.dumps(data, indent=2)}\n```\n\n"

                content += "---\n\n"

            (self.run_dir / "agents" / f"{agent}.md").write_text(content)

    def _write_findings(self):
        """Write findings report."""
        content = f"""# Security Findings

## Target: {self.target_url}
## Date: {datetime.now().strftime("%Y-%m-%d")}

---

"""
        if self.findings:
            # Group by severity
            by_severity = {"critical": [], "high": [], "medium": [], "low": [], "info": []}
            for f in self.findings:
                sev = f.get("severity", "info").lower()
                if sev in by_severity:
                    by_severity[sev].append(f)

            for severity in ["critical", "high", "medium", "low", "info"]:
                findings = by_severity[severity]
                if findings:
                    content += f"## {severity.upper()} Severity\n\n"
                    for f in findings:
                        content += f"### {f.get('title', 'Untitled')}\n\n"
                        content += f"**Description:** {f.get('description', 'N/A')}\n\n"
                        if f.get("evidence"):
                            content += f"**Evidence:**\n```\n{f['evidence']}\n```\n\n"
                        if f.get("recommendation"):
                            content += f"**Recommendation:** {f['recommendation']}\n\n"
                        content += "---\n\n"
        else:
            content += "No specific vulnerabilities were identified during this assessment.\n\n"
            content += "This could mean:\n"
            content += "1. The target has good security posture\n"
            content += "2. More thorough testing may be needed\n"
            content += "3. Some vulnerabilities require manual verification\n"

        content += "\n## Recommendations\n\n"
        content += "1. Conduct regular security assessments\n"
        content += "2. Implement security headers (CSP, X-Frame-Options, etc.)\n"
        content += "3. Use parameterized queries to prevent SQL injection\n"
        content += "4. Sanitize all user input to prevent XSS\n"
        content += "5. Implement proper access controls\n"

        (self.run_dir / "findings" / "vulnerabilities.md").write_text(content)

    def _write_raw_events(self):
        """Write raw events JSON."""
        (self.run_dir / "raw" / "events.json").write_text(
            json.dumps(self.events, indent=2, default=str)
        )


def convert_localhost_for_docker(url: str) -> str:
    """Convert localhost URLs to host.docker.internal for Docker containers."""
    import platform
    import re

    # On macOS/Windows, Docker containers need host.docker.internal to reach host
    if platform.system() in ("Darwin", "Windows"):
        # Replace localhost or 127.0.0.1 with host.docker.internal
        url = re.sub(r'(https?://)localhost(:\d+)?', r'\1host.docker.internal\2', url)
        url = re.sub(r'(https?://)127\.0\.0\.1(:\d+)?', r'\1host.docker.internal\2', url)

    return url


async def run_pentest(target_url: str, output_dir: Path, verbose: bool = True, skip_recon_path: Optional[str] = None):
    """Run a penetration test via CLI."""
    import uuid

    from langchain_core.runnables import RunnableConfig
    from langchain_core.messages import HumanMessage

    from src.config.settings import get_config
    from src.state.graph_state import (
        FennecState, SessionContext, ContainerInfo, AgentType,
    )
    from src.docker.client import DockerClient, ContainerConfig
    from src.graph import compile_role_based_graph

    # Convert localhost to host.docker.internal for Docker access
    docker_target_url = convert_localhost_for_docker(target_url)

    config = get_config()
    print(f"\n{'='*60}")
    print("  Fennec AI - Red Team Penetration Testing")
    print(f"{'='*60}")
    print(f"Target: {target_url}")
    if docker_target_url != target_url:
        print(f"Docker Target: {docker_target_url}")
    print(f"Output: {output_dir}")
    print(f"{'='*60}\n")

    # Initialize Docker
    print("Initializing Docker...")
    docker_client = DockerClient()
    await docker_client.initialize()

    # Initialize LLM
    print("Initializing LLM...")
    if config.llm_provider == "anthropic":
        from langchain_anthropic import ChatAnthropic
        llm = ChatAnthropic(
            model=config.llm_model,
            api_key=config.anthropic_api_key,
            temperature=config.llm_temperature,
            max_tokens=config.llm_max_tokens,
            timeout=config.llm_timeout,
        )
    elif config.llm_provider == "openrouter":
        from langchain_openai import ChatOpenAI
        llm = ChatOpenAI(
            model=config.llm_model,
            api_key=config.openrouter_api_key,
            base_url=config.openrouter_base_url,
            temperature=config.llm_temperature,
            max_tokens=config.llm_max_tokens,
            timeout=config.llm_timeout,
            max_retries=config.llm_max_retries,
            default_headers={
                "HTTP-Referer": "https://fennec.ai",
                "X-Title": "Fennec AI",
            },
        )
    else:
        from langchain_openai import ChatOpenAI
        llm = ChatOpenAI(
            model=config.llm_model,
            api_key=config.openai_api_key,
            temperature=config.llm_temperature,
            max_tokens=config.llm_max_tokens,
            timeout=config.llm_timeout,
            max_retries=config.llm_max_retries,
        )

    # Create container
    print("Creating Kali Linux container...")
    session_id = str(uuid.uuid4())
    container_config = ContainerConfig(
        image=config.docker_image,
        name=f"fennec-cli-{session_id[:8]}",
    )

    try:
        container_id = await docker_client.spawn_container(container_config)
        print(f"   Container ID: {container_id[:12]}")
    except Exception as e:
        print(f"Failed to create container: {e}")
        print("   Make sure Docker Desktop is running.")
        await docker_client.close()
        return

    # Initialize report generator
    report = ReportGenerator(output_dir, target_url, session_id)

    # Create session and state
    session = SessionContext(
        session_id=session_id,
        flow_id=str(uuid.uuid4()),
        container=ContainerInfo(
            container_id=container_id,
            image=config.docker_image,
        ),
        docker_image=config.docker_image,
        language="en",
    )

    # Load pre-built recon data if provided
    recon_data = None
    if skip_recon_path:
        with open(skip_recon_path, "r") as f:
            recon_data = json.load(f)
        print(f"📋 Loaded recon data from {skip_recon_path} — skipping recon phase")

    initial_state: FennecState = {
        "session": session,
        # Use docker_target_url for the actual test (runs in container)
        "messages": [HumanMessage(content=f"Perform penetration testing on: {docker_target_url}")],
        "next_agent": AgentType.ORCHESTRATOR,
        "should_continue": True,
        "final_result": None,
        "success": False,
        # Keep original target_url for reporting
        "target_url": target_url,
        "recon_data": recon_data,
    }

    runnable_config = RunnableConfig(
        configurable={
            "llm": llm,
            "docker_client": docker_client,
            "container_id": container_id,
            "working_dir": "/work",
            "tavily_api_key": config.tavily_api_key,
            "perplexity_api_key": config.perplexity_api_key,
        },
        recursion_limit=100,  # Increase from default 25
    )

    # Compile graph
    print("Compiling agent graph...")
    graph = compile_role_based_graph()

    # Run the graph
    print("\nStarting penetration test...\n")
    print("-" * 60)

    current_agent = "orchestrator"

    try:
        async for event in graph.astream(initial_state, runnable_config):
            for node_name, node_output in event.items():
                # Update current agent
                if node_output.get("next_agent"):
                    next_agent = node_output["next_agent"]
                    current_agent = next_agent.value if hasattr(next_agent, 'value') else str(next_agent)

                # Log node update
                report.log_event("node_update", {"node": node_name}, current_agent)

                if verbose:
                    print(f"\n[{current_agent.upper()}]")

                # Process messages
                messages = node_output.get("messages", [])
                for msg in messages:
                    if hasattr(msg, "content") and msg.content:
                        msg_type = type(msg).__name__
                        content = str(msg.content)[:500]

                        report.log_event("message", {
                            "type": msg_type,
                            "content": msg.content,
                        }, current_agent)

                        if verbose:
                            if msg_type == "AIMessage":
                                print(f"  > {content}")
                            elif msg_type == "ToolMessage":
                                print(f"  << {content[:200]}...")

                    if hasattr(msg, "tool_calls") and msg.tool_calls:
                        for tc in msg.tool_calls:
                            tool_name = tc.get("name", "unknown")
                            tool_args = tc.get("args", {})

                            report.log_event("tool_call", {
                                "name": tool_name,
                                "args": tool_args,
                            }, current_agent)

                            if verbose:
                                print(f"  -> Calling: {tool_name}")

                # Process final result
                if node_output.get("final_result"):
                    result = {
                        "success": node_output.get("success", False),
                        "result": str(node_output.get("final_result", "")),
                    }
                    report.set_result(result)

                    if verbose:
                        status = "SUCCESS" if result["success"] else "FAILED"
                        print(f"\n  Final Result: {status}")
                        print(f"     {result['result'][:300]}...")

        print("\n" + "-" * 60)
        print("Penetration test completed!")

    except Exception as e:
        print(f"\nError during pentest: {e}")
        import traceback
        traceback.print_exc()
        report.log_event("error", {"error": str(e)}, "system")

    finally:
        # Cleanup
        print("\nCleaning up...")
        try:
            await docker_client.delete_container(container_id, force=True)
            print(f"   Removed container: {container_id[:12]}")
        except Exception as e:
            print(f"   Warning: Could not remove container: {e}")

        await docker_client.close()

        # Generate reports
        print("\nGenerating reports...")
        report.generate_reports()


# ─── CLI Commands ──────────────────────────────────────────────────────────────

def cmd_scan(args):
    """Handle the scan command."""
    from src.config.settings import get_config

    # If --test-model, override env to use cheap OpenRouter model
    if args.test_model:
        os.environ["LLM_PROVIDER"] = "openrouter"
        os.environ["LLM_MODEL"] = "mistralai/mistral-small-3.1-24b-instruct"
        if not os.environ.get("OPENROUTER_API_KEY"):
            print("Error: OPENROUTER_API_KEY environment variable is required for --test-model")
            sys.exit(1)
        get_config.cache_clear()

    # Resolve output path
    output_dir = Path(args.output)
    if not output_dir.is_absolute():
        output_dir = Path(project_dir) / args.output
    output_dir = output_dir.resolve()

    # Run pentest
    asyncio.run(run_pentest(
        target_url=args.target,
        output_dir=output_dir,
        verbose=not args.quiet,
        skip_recon_path=args.skip_recon,
    ))


# ─── Main Entry Point ─────────────────────────────────────────────────────────

def main():
    from cli.art import print_banner
    print_banner()

    parser = argparse.ArgumentParser(
        description="Fennec AI - Autonomous Penetration Testing Framework",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  fennec scan --target http://localhost:9000
  fennec scan --target https://example.com --output ./reports
        """
    )

    subparsers = parser.add_subparsers(dest="command")

    # scan
    scan_parser = subparsers.add_parser("scan", help="Run a penetration test")
    scan_parser.add_argument(
        "--target", "-t", required=True,
        help="Target URL to test (e.g., http://localhost:9000)"
    )
    scan_parser.add_argument(
        "--output", "-o", default="../output",
        help="Output directory for reports (default: ../output)"
    )
    scan_parser.add_argument(
        "--quiet", "-q", action="store_true",
        help="Quiet mode - minimal output"
    )
    scan_parser.add_argument(
        "--test-model", action="store_true",
        help="Use a cheap OpenRouter model for testing"
    )
    scan_parser.add_argument(
        "--skip-recon", type=str, default=None,
        help="Path to a JSON file with pre-built recon data (skips recon phase)"
    )

    # Backward compatibility: if --target is used without a subcommand
    # e.g., `python cli.py --target URL`
    if len(sys.argv) > 1 and sys.argv[1].startswith("--target") or (
        len(sys.argv) > 1 and sys.argv[1] == "-t"
    ):
        # Inject 'scan' as the subcommand
        sys.argv.insert(1, "scan")

    args = parser.parse_args()

    if args.command == "scan":
        cmd_scan(args)
    else:
        parser.print_help()
        sys.exit(0)


if __name__ == "__main__":
    main()
